bootstrap_common: &bootstrap_common
  pull: true
  commands:
    - mkdir -p /opt/metwork-mfext-${DRONE_BRANCH}
    - ./bootstrap.sh /opt/metwork-mfext-${DRONE_BRANCH}
    - cat adm/root.mk
    
build_common: &build_common
  commands:
    - export METWORK_BUILD_OS=${OS_VERSION}
    - mkdir -p /opt/metwork-mfext-${DRONE_BRANCH}
    - mkdir -p /pub/metwork/continuous_integration/buildlogs/${DRONE_BRANCH}/mfext/${OS_VERSION}/${DRONE_BUILD_NUMBER}
    - make >/pub/metwork/continuous_integration/buildlogs/${DRONE_BRANCH}/mfext/${OS_VERSION}/${DRONE_BUILD_NUMBER}/make.log 2>&1
    - make doc
    - rm -Rf html_doc
    - cp -Rf /opt/metwork-mfext-${DRONE_BRANCH}/html_doc .
    - make test
    - make RELEASE_BUILD=${DRONE_BUILD_NUMBER} rpm
    - mv /opt/metwork-mfext-${DRONE_BRANCH}/*.rpm .
  volumes:
    - /buildcache:/buildcache
    - /pub:/pub
    
publish_ci_common: &publish_ci_common
  commands:
    - mkdir -p /pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}/
    - cp *.rpm /pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}/
    - yum -y install createrepo
    - createrepo --update /pub/metwork/continuous_integration/rpms/${DRONE_BRANCH}/${OS_VERSION}
    - if test "${OS_VERSION}" = "centos6"; then rm -Rf /pub/metwork/continuous_integration/docs/${DRONE_BRANCH}/mfext; mkdir -p /pub/metwork/continuous_integration/docs/${DRONE_BRANCH}/mfext ; cp -Rf html_doc/* /pub/metwork/continuous_integration/docs/${DRONE_BRANCH}/mfext/ ; fi
  volumes:
    - /pub:/pub
    
trigger_common: &trigger_common
  image: plugins/downstream
  fork: true
  secrets: [ downstream_token, downstream_server ]


pipeline:
  bootstrap_integration:
    <<: *bootstrap_common
    image: metwork/mfext-${OS_VERSION}-buildimage:integration
    when:
      event: [push]
      branch: integration
  bootstrap:
    <<: *bootstrap_common
    image: metwork/mfext-${OS_VERSION}-buildimage:master
    when:
      event: [push]
      branch:
        exclude: [ integration ]
  build_integration:
    <<: *build_common
    image: metwork/mfext-${OS_VERSION}-buildimage:integration
    when:
      event: [push]
      branch: integration
  build:
    <<: *build_common
    image: metwork/mfext-${OS_VERSION}-buildimage:master
    when:
      event: [push]
      branch:
        exclude: [ integration ]
  publish_ci_integration:
    <<: *build_ci_common
    image: metwork/mfext-${OS_VERSION}-buildimage:integration
    when:
      event: [push]
      branch: integration
  publish_ci:
    <<: *build_ci_common
    image: metwork/mfext-${OS_VERSION}-buildimage:master
    when:
      event: [push]
      branch:
        exclude: [ integration ]
  trigger_integration
    <<: *trigger_common
    repositories:
      - metwork-framework/docker-mfcom-${OS_VERSION}-buildimage@integration
    when:
      status: [ success ]
      event: push
      branch: integration
  trigger_master
    <<: *trigger_common
    repositories:
      - metwork-framework/docker-mfcom-${OS_VERSION}-buildimage@master
    when:
      status: [ success ]
      event: push
      branch: master


matrix:
  OS_VERSION:
    - centos6
    - centos7
